# Tailscale Kubernetes Operator
# Provides selective Tailscale networking for pods that need internet access

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: tailscale-operator
    app.kubernetes.io/component: networking
    project: networking
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: networking
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: 1.86.2  # Latest stable version
    helm:
      values: |
        # Tailscale operator configuration
        
        # Operator configuration
        operatorConfig:
          image:
            repository: "tailscale/tailscale"
            tag: "v1.86.2"
        
        # RBAC configuration
        rbac:
          create: true
        
        # Service account
        serviceAccount:
          create: true
          name: tailscale-operator
        
        # Resource limits
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        
        # Node selection
        nodeSelector: {}
        
        # Tolerations
        tolerations: []
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        
        # Default configuration for Tailscale devices
        defaultTags:
          - "k8s"
          - "apollo"
          - "operator"

  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale-operator
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  revisionHistoryLimit: 10
  
status: {}