apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
  labels:
    app.kubernetes.io/name: infisical
    app.kubernetes.io/component: secrets-management
    project: storage
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: storage
  source:
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    chart: infisical-standalone
    targetRevision: 1.6.1  # Use the standalone chart with PostgreSQL support
    helm:
      values: |
        # Infisical standalone configuration for Apollo home lab
        
        infisical:
          enabled: true
          replicaCount: 2
          
          # Use PostgreSQL version of Infisical
          image:
            repository: infisical/infisical
            tag: "v0.93.1-postgres"
            pullPolicy: IfNotPresent
          
          # Service configuration for NodePort access
          service:
            type: NodePort
            nodePort: "30500"
          
          # Resource limits for home lab
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
        
        # PostgreSQL configuration
        postgresql:
          enabled: true
          auth:
            username: infisical
            password: infisical
            database: infisical
            postgresPassword: postgres-admin-password
          primary:
            persistence:
              enabled: true
              storageClass: "local-path"
              size: 8Gi
        
        # Redis configuration  
        redis:
          enabled: true
          auth:
            enabled: false
          master:
            persistence:
              enabled: true
              storageClass: "local-path"
              size: 2Gi
        
        # Disable ingress since we use NodePort
        ingress:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  revisionHistoryLimit: 10