---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql
  namespace: infisical
spec:
  encryptedData:
    postgres-password: AgDZXHsSjjriXI2bWJqDlHDm5Oefr5+QVln6oUDEen2le3j3tkoUS+EUpOjJsFFVjO1gYcFeoWy+k8aZBr31FEf8vpzW+TtMfFpnzy6pWb9NLjq3NCQ0rcjls0jW2V1uE4aWoGwp/7A0/4ZcshcbEqMeVXZECCAfmvBPMjlHEkI0bis4j9A2JJ0yJlREIT63vNnzenpZwrY+qk4B9zNi1LolwMN8i5BqPPKfrp6n6+Ighi0bzMot85UusqvcnudWUC86QN2IsjIR+r6HyprJEiA5Ie+9oSWbwDm8ipGbSi4PECxiIhtDDbLjMmx9ukQ0AwCwmeIFCp1aaMyAiz29zjph8BRZTWX2PVNmNFaxvkrWQQw8Hv3+/6srBTncq/3xwc1obroRacx7/YGB3VEDzgTZbm6++4yZAdHLnhNFopH0kkBLrPHZaOkX5zPyW39WR82ngMUilbEpMkZUNIp89A3Me5bF+cYo1ga8EYhYikLAl0S/Z5EQM+uxyxq0PTonUMnKzTQZvYKS4mHwECa9oHzRIXQ0Fg/j/ceUuOKngjK2/2NWwjxn1aWEM5ptC2GN3uqu5Jn0v/I9besRR1ogN+MdvhqXx0FYmt1Q/AtOCMeE7/Z8rZXAAhXKtwpKf9WF2xxxO1BvN63FMIGlWKZwLxRqXoEBiL9R4CEhC6uaaajT/p2IKJxxZG3YRGcJCT2yBA4h12jRbapCr4E=
  template:
    metadata:
      creationTimestamp: null
      name: postgresql
      namespace: infisical
    type: Opaque
