# RBAC resources for Actions Runner Controller
# These need to be created before the Helm chart is deployed

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-runner-controller
  namespace: github-runners
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: actions-runner-controller
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before controller
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["actions.summerwind.dev"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: actions-runner-controller
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: actions-runner-controller
subjects:
- kind: ServiceAccount
  name: actions-runner-controller
  namespace: github-runners

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: actions-runner-controller-leader-election
  namespace: github-runners
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before controller
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: actions-runner-controller-leader-election
  namespace: github-runners
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: actions-runner-controller-leader-election
subjects:
- kind: ServiceAccount
  name: actions-runner-controller
  namespace: github-runners

---
# Additional ClusterRole that the Helm chart expects
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gh-actions-runner-controller-runner-viewer
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["actions.summerwind.dev"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gh-actions-runner-controller-runner-viewer
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gh-actions-runner-controller-runner-viewer
subjects:
- kind: ServiceAccount
  name: actions-runner-controller
  namespace: github-runners