# RBAC for GitHub runners to use Docker Buildx with Kubernetes driver
# This allows the runner service account to create BuildKit deployments

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: buildx-permissions
  namespace: github-runners
rules:
# Permissions for Docker Buildx to create and manage BuildKit deployments
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildx-permissions
  namespace: github-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: buildx-permissions
subjects:
- kind: ServiceAccount
  name: apollo-runners-gha-rs-no-permission
  namespace: github-runners