apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama3
  namespace: argocd
  labels:
    app.kubernetes.io/name: llama3
    app.kubernetes.io/component: ai-model
    project: ai
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ai
  source:
    repoURL: https://github.com/matthewmyrick/apollo-iac
    targetRevision: HEAD
    path: kubernetes/applications/llama3/deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: llama3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
status: {}
