# Actions Runner Controller Helm Chart
# Deploy this SECOND (after RBAC) to install CRDs and controller

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: github-actions-controller
    app.kubernetes.io/component: controller
    project: integrations
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: integrations
  source:
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    chart: actions-runner-controller
    targetRevision: 0.27.4  # More recent stable version
    helm:
      parameters:
        # Basic controller configuration
        - name: "authSecret.enabled"
          value: "true"
        - name: "authSecret.name"
          value: "controller-manager"
        
        # Resource limits
        - name: "resources.requests.cpu"
          value: "100m"
        - name: "resources.requests.memory"
          value: "128Mi"
        - name: "resources.limits.cpu"
          value: "500m"
        - name: "resources.limits.memory"
          value: "256Mi"
        
      values: |
        # Simplified controller configuration
        fullnameOverride: "gh-actions-runner-controller"
        
        # Use existing service account
        serviceAccount:
          create: false
          name: actions-runner-controller
        
        # Let Helm create the RBAC it needs
        rbac:
          create: true
        
        # Basic settings
        logLevel: info
        
        # Resource configuration
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: github-runners
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  revisionHistoryLimit: 10
  
status: {}