# GitHub Actions Runner Scale Set Controller (ARC)
# Deploy this SECOND (after RBAC) to install CRDs and controller
# This uses the new GitHub-supported gha-runner-scale-set architecture

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: github-actions-controller
    app.kubernetes.io/component: controller
    project: integrations
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: integrations
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    targetRevision: 0.12.1  # Latest stable version (Jun 2024)
    helm:
      values: |
        # gha-runner-scale-set-controller configuration
        # This is the new GitHub-supported architecture
        
        # Controller configuration
        controllerManagerConfigYaml: |
          controller:
            leaderElection:
              enabled: true
              namespace: github-runners
          metrics:
            bindAddress: 0.0.0.0:8080
          webhook:
            port: 9443
        
        # Service account configuration
        serviceAccount:
          create: false
          name: actions-runner-controller
        
        # Resource configuration
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        
        # Security context
        securityContext:
          runAsNonRoot: true

  destination:
    server: https://kubernetes.default.svc
    namespace: github-runners
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  revisionHistoryLimit: 10
  
status: {}