apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: llama3
  labels:
    app: ollama
spec:
  type: NodePort
  selector:
    app: ollama
  ports:
  - port: 11434
    targetPort: 11434
    nodePort: 30434
    protocol: TCP
    name: http