apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terraform-state-ingress
  namespace: terraform-state
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "terraform-state"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: tailscale
  rules:
  - host: terraform-state.tailnet
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: terraform-state-service
            port:
              number: 9000
      - path: /console
        pathType: Prefix
        backend:
          service:
            name: terraform-state-service
            port:
              number: 9001
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: terraform-state
stringData:
  TS_AUTHKEY: "YOUR_TAILSCALE_AUTH_KEY_HERE"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-ingress
  namespace: terraform-state
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-ingress
  template:
    metadata:
      labels:
        app: tailscale-ingress
    spec:
      containers:
      - name: tailscale
        image: tailscale/tailscale:latest
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        - name: TS_KUBE_SECRET
          value: "tailscale-state"
        - name: TS_USERSPACE
          value: "false"
        - name: TS_HOSTNAME
          value: "terraform-state"
        - name: TS_SERVE_CONFIG
          value: |
            {
              "TCP": {
                "443": {
                  "HTTPS": true
                }
              },
              "Web": {
                "terraform-state.tailnet:443": {
                  "Handlers": {
                    "/": {
                      "Proxy": "http://terraform-state-service.terraform-state.svc.cluster.local:9000"
                    },
                    "/console": {
                      "Proxy": "http://terraform-state-service.terraform-state.svc.cluster.local:9001"
                    }
                  }
                }
              }
            }
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi