# GitHub Runner Scale Set
# Deploy this THIRD (after controller) to create actual runner scale sets
# This uses the new GitHub-supported gha-runner-scale-set architecture

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-runners
  namespace: argocd
  labels:
    app.kubernetes.io/name: github-actions-runners
    app.kubernetes.io/component: runners
    project: integrations
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: integrations
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: 0.12.1  # Latest stable version (Jun 2024)
    helm:
      values: |
        # GitHub Runner Scale Set Configuration
        # Replace these values with your actual GitHub configuration
        
        # Controller service account reference
        controllerServiceAccount:
          name: github-actions-controller-gha-rs-controller
          namespace: github-runners
        
        # GitHub repository configuration (for repo-level runners)
        githubConfigUrl: "https://github.com/matthewmyrick/apollo-iac"  # Point to specific repo
        
        # GitHub authentication - reference pre-existing secret
        # The secret must exist in the same namespace with key: github_token
        githubConfigSecret: github-runner-token
        
        # Runner configuration
        minRunners: 0
        maxRunners: 5
        
        # Custom runner scale set name (this becomes a label)
        runnerScaleSetName: "apollo-runners"
        
        
        # Container mode for Docker support
        containerMode:
          type: "dind"  # Docker-in-Docker support
        
        # Runner template configuration
        template:
          metadata:
            labels:
              environment: "home-lab"
              project: "apollo-iac"
            annotations:
              # Enable Tailscale networking for internet access
              tailscale.com/expose: "false"  # Don't expose to Tailscale network, just use for egress
              tailscale.com/tags: "tag:k8s,tag:github-runner"
          spec:
            # Temporarily use host network until Tailscale operator is fixed
            hostNetwork: true
            dnsPolicy: ClusterFirstWithHostNet
            containers:
            - name: runner
              image: "ghcr.io/actions/actions-runner:latest"
              resources:
                requests:
                  cpu: "100m"
                  memory: "256Mi"
                limits:
                  cpu: "500m"
                  memory: "1Gi"
              # Environment variables (Tailscale handles routing automatically)
              env: []
        
        # Autoscaling behavior
        autoscaling:
          scaleDownDelaySecondsAfterScaleOut: 300
          scaleUpTriggers:
          - github_webhook
          - poll_interval
        
        # Logging
        logging:
          level: "info"
  destination:
    server: https://kubernetes.default.svc
    namespace: github-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
status: {}