# GitHub Actions Runners for Portfolio Site
# Using the new GitHub Actions Runner Controller API

apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: portfolio-github-runners
  namespace: github-runners
  labels:
    app: portfolio-github-runners
    env: production
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy after controller
spec:
  # GitHub configuration
  githubConfigUrl: https://github.com/matthewmyrick/portfolio-site
  githubConfigSecret: github-token
  
  # Minimum and maximum number of runners
  minRunners: 0
  maxRunners: 2
  
  # Runner template
  template:
    spec:
      containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        env:
        - name: RUNNER_FEATURE_FLAG_ONCE
          value: "true"
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 4Gi
        volumeMounts:
        - name: work
          mountPath: /runner/_work
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: false
      
      volumes:
      - name: work
        emptyDir: {}
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      
      # Security context
      securityContext:
        runAsUser: 1001
        runAsGroup: 121  # docker group
        fsGroup: 121
      
      # Node selector (optional - run on specific nodes)
      nodeSelector: {}
      
      # Tolerations (optional - allow scheduling on tainted nodes)
      tolerations: []